#!/bin/bash
export LOC_CHAR=`locale charmap`

# Detects tool
XGETTEXT=`which xgettext 2> /dev/null`
MSGCAT=`which msgcat 2> /dev/null`
MSGMERGE=`which msgmerge 2> /dev/null`
MSGATTRIB=`which msgattrib 2> /dev/null`
MSGGREP=`which msggrep 2> /dev/null`

# Configuration file for paths
source tools/i18n.cfg

if [ ${LOC_CHAR} = "C" ] || [ ${LOC_CHAR} = "ANSI_X3.4-1968" ]; then
   echo "Your locale is not correctly configured: ${LOC_CHAR}" >&2
   exit -1
fi

# Show usage information
usage()
{
    NAME=`basename $0`
    cat <<EOT
$NAME path
  Update translations of PO files stored in path with current source code
    -h            Print this help message
    -i            Ignore PO files header update
    path          parent directory that will be run through to find PO files (optional)

  Default PO directory:
    $PODIR
EOT
}


# Verify tools
if [ -z "${XGETTEXT}" -o ! -f "${XGETTEXT}" ]; then
    echo "Missing xgettext tool" >&2
    exit 1
fi

if [ -z "${MSGCAT}" -o ! -f "${MSGCAT}" ]; then
    echo "Missing msgcat tool" >&2
    exit 1
fi

if [ -z "${MSGMERGE}" -o ! -f "${MSGMERGE}" ]; then
    echo "Missing msgmerge tool" >&2
    exit 1
fi

if [ -z "${MSGATTRIB}" -o ! -f "${MSGATTRIB}" ]; then
    echo "Missing msgattrib tool" >&2
    exit 1
fi

if [ -z "${MSGGREP}" -o ! -f "${MSGGREP}" ]; then
    echo "Missing msggrep tool" >&2
    exit 1
fi

# Parse the command line and update configuration
while [ ! $# -eq 0 ]; do
	case "$1" in
	  -i)
		OMITHD="--omit-header"
		echo "ignore date time update $1 ${PODIR}" >&2
		;;
	  -h)
        usage
        exit 0
        ;;
	  *)
		# Update optional PO dir
		PODIR="$1"
        if [ ! -d "$PODIR" ]; then
            usage
            echo "Invalid PO folder name: $PODIR" >&2
            exit 1
        fi
		;;
	esac
	shift
done

# Get all po files to be updated
POLIST=`find ${PODIR} -name "*.po"`

mkdir -p "${TMPDIR}"

# Retreive the string from 
find ./ -type f -not -path "*.svn*" \
       -name "*.py" | sort -n | \
    xargs ${XGETTEXT} -s --no-location -C --keyword=localize --keyword=n_:1,2 \
          --keyword=RN_ ${OMITHD} --add-comments=- -o ${TMPDIR}/messages_tmp.po

if [ $? -ne 0 ]; then
    echo "Error when analysing source code" >&2
    exit 1
fi

# Setting the charset of the local environment
sed "s/^\"Content-Type:\ text\/plain;\ charset=CHARSET/\
\"Content-Type:\ text\/plain;\ charset=${LOC_CHAR}/" \
${TMPDIR}/messages_tmp.po > ${TMPDIR}/messages.po


for pofile in ${POLIST};
do
    echo "Updating $pofile"

    # Merging with already translated strings
    # --backup=off has been added because of gettext v0.17 bug on OSX
    msgmerge --update --no-fuzzy-matching --width=80 --backup=off\
             $pofile \
             ${TMPDIR}/messages.po

    if [ $? -ne 0 ]; then
        echo "Error when updating translations for $pofile" >&2
        exit 1
    fi

    # Remove obsolete messages (that contains autogenerated keys)
    msgattrib --no-obsolete \
             $pofile \
             -o $pofile
             
    if [ $? -ne 0 ]; then
        echo "Error when removing obsolete translations for $pofile" >&2
        exit 1
    fi

    name=$(echo $pofile | cut -f 1 -d '.')
    msgfmt $pofile -o $name".mo"

done;

rm -rf "${TMPDIR}"

exit 0

